name: dremfoo
description: Construindo sonhos

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## LIBS ##
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  connectivity: ^0.4.6+2 #verificar conexão com internet - no web
  shared_preferences: ^0.5.6+1
  cached_network_image: ^2.0.0
  provider: ^3.1.0+1
  flutter_auth_buttons: ^0.6.0
  bloc_pattern: ^2.5.1
  flare_flutter: ^2.0.1 # animações
  loading: ^1.0.2
  flutter_native_image: ^0.0.5
  fl_chart: ^0.9.4
  date_util: ^0.1.4

  #Exigem configuração no Android ou IOS
  image_picker: ^0.6.3+1

  #Firebase
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0
  cloud_firestore: ^0.13.3
  firebase_storage: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Alata
      fonts:
        - asset: assets/fonts/Alata-Regular.ttf

    - family: ShadowsIntoLight
      fonts:
        - asset: assets/fonts/ShadowsIntoLight-Regular.ttf

    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
