name: dremfoo
description: Construindo sonhos

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## LIBS ##
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  connectivity: ^3.0.6 #verificar conexão com internet - no web
  shared_preferences: ^2.0.7
  cached_network_image: ^3.2.1
  provider: ^6.0.3
  sign_button: ^2.0.2
#  bloc_pattern: ^3.0.0
  flare_flutter: ^3.0.2 # animações
  flutter_native_image: ^0.0.6+1
  fl_chart: ^0.51.0
  date_format: ^2.0.6
  email_launcher: ^1.1.1
  flutter_share: ^2.0.0
#  share_files_and_screenshot_widgets_plus: ^1.0.3 //Descomentar depois de migrar para null safe
#  share: ^2.0.4 //Descomentar depois de migrar para null safe
  flutter_local_notifications: ^9.6.0
  path_provider: ^2.0.10
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.10
  flutter_native_timezone: ^2.0.0
  pixabay_picker: ^1.0.6
  youtube_player_flutter: ^8.1.0
  percent_indicator: ^3.4.0
  font_awesome_flutter: ^10.1.0

  #Exigem configuração no Android ou IOS
  image_picker: ^0.8.4+1

  #Firebase
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.7
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5
  firebase_messaging: ^11.2.5
  firebase_in_app_messaging: ^0.6.0+6
  firebase_analytics: ^9.0.5
  firebase_crashlytics: ^2.4.5
  firebase_remote_config: ^1.0.4

  #Mobx
  flutter_mobx: ^2.0.2
  mobx: ^2.0.4

  flutter_modular: ^5.0.3
  slidy: ^3.2.2+2

  intl: ^0.17.0

  google_fonts: ^2.1.0

  google_mobile_ads: ^0.13.6

  in_app_review: ^2.0.3

  in_app_purchase: ^2.0.1


dev_dependencies:
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.2
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  flutter_modular_test:




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  fonts:
    - family: Alata
      fonts:
        - asset: assets/fonts/Alata-Regular.ttf

    - family: ShadowsIntoLight
      fonts:
        - asset: assets/fonts/ShadowsIntoLight-Regular.ttf

    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/

scripts:
  mobx: flutter pub run build_runner watch  --delete-conflicting-outputs


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
